function [Mcmc]=flearnstruct_cmat(Param,savefile)
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here

% specify paramter
hprior = Param.hprior;
pa_limit = Param.pa_limit;
nsamples = Param.nstep;
burnin = Param.burnin;
thinning = Param.thinning;
method = Param.mcmethod;
runt = Param.runt;



LS = readLS( Param );
N=length(LS);
Hprior = ones(N);
Hprior = setdiag(Hprior,0);

if ~strcmp('no',hprior)
    temp=load(Param.savepath.hprior);
    Hprior=temp.Hprior.skeleton;
end
Hprior=full(Hprior);


init_dag = mk_rnd_dag(N,pa_limit);
init_dag = double(init_dag&Hprior);
switch method,
    case 'rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1/15,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'fullrev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'revorg'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4_org('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1/15,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'fullrevorg'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4_org('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'struct'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'Mstruct'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);

        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            [Mcmc.sampled_graphs(i), Mcmc.LL(i)] =...
                learn_struct_mcmc_MH2('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'hprior',Hprior,...
                'nsamples', nsamples, 'burnin', burnin,...
                'thinning',nsamples+burnin);
            
            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
    case 'jun'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);
        
        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            [sampled_graphs, LL] =...
                learn_struct_mcmc_gibbs_zhu2('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'hprior',Hprior,...
                'nsamples', nsamples, 'burnin', burnin,'thinning',thinning);
            Mcmc.sampled_graphs(i)=sampled_graphs(find(LL==max(LL),1,'last'));
            Mcmc.LL(i)=max(LL);
            
            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
        
    case '2gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '1gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0,...
            'pr',0,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'revgibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',0.25,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'fullrevgibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'Mfullrevgibbs'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);
        
        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            [Mcmc.sampled_graphs(i), Mcmc.LL(i)] =...
                learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'rev',1,...
                'pr',1,...
                'hprior',Hprior,...
                'nsamples', nsamples, 'burnin', burnin,...
                'thinning',nsamples+burnin);    
            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
    case '2gibbs25'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block12_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0,...
            'pr',0.25,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '3gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '3gibbsrev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',0.25,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'full3gibbsrev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '4gibbsrev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',0.25,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'full4gibbsrev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',1,...
            'pr',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '25rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.25,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '50rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.50,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '65rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.65,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '75rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.75,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '85rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.85,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case '95rev'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL, Mcmc.accept_ratio] =...
            learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'rev',0.95,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case  'M95rev'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);
        
        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            [Mcmc.sampled_graphs(i), Mcmc.LL(i)] =...
                learn_struct_mcmc_MH_REVmove4('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'rev',0.95,...
                'hprior',Hprior,...
                'nsamples', nsamples, 'burnin', burnin,...
                'thinning',nsamples+burnin);

            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
    case 'indeg4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_degselct_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
    case 'outdeg4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_degselct_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',2,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
    case 'todeg4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_degselct_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',3,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;

    case 'todeg4gibbs_v2'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_todeg_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
    case 'indeg3gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_degselct_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',1,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
    case 'outdeg3gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_degselct_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',2,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
    case 'todeg3gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_degselct_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'deg',3,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'todeg3gibbs_v2'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block123_todeg_v4_3('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'todeg_w_4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_todeg_w_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'outdeg_w_4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_outdeg_w_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'todeg_w_4gibbs_v2'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_todeg_w_v4_3('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'outdeg_w_4gibbs_v2'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_outdeg_w_v4_3('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
        
    case 'lin-4gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_lin_v4_1('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'maxlen',3,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'lin-3gibbs'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_gibbs_block1234_lin_v4_2('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'maxlen',2,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'Mlin-3gibbs'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);
        
        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            
            [Mcmc.sampled_graphs(i), Mcmc.LL(i)] =...
                learn_struct_mcmc_gibbs_block1234_lin_v4_1('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'hprior',Hprior,...
                'maxlen',2,...
                'nsamples', nsamples, 'burnin', burnin,...
                'thinning',nsamples+burnin);

            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
    case 'pathrev_debugged'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_MH_PathREV_v4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'rev',0.50,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
        
    case 'Mpathrev'
        numtry=Param.paramcmc_runnum;
        Mcmc.sampled_graphs=cell(numtry,1);
        Mcmc.LL=-inf(numtry,1);
        
        tic
        for i=1:numtry
            i
            init_dag = mk_rnd_dag(N,pa_limit);
            init_dag = double(init_dag&Hprior);
            
            [Mcmc.sampled_graphs(i), Mcmc.LL(i)] =...
                learn_struct_mcmc_MH_PathREV_v4('LS',LS, 'init_dag',init_dag,...
                'pa_limit',pa_limit,...
                'hprior',Hprior,...
                'rev',0.50,...
                'nsamples', nsamples, 'burnin', burnin,...
                'thinning',nsamples+burnin);

            if toc >runt
                break;
            end
        end
        Mcmc.toc=toc;
        
    case 'seqrevsrc'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_MH_SeqREVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'rev',0.50,...
            'edirec',1,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;   
    case 'seqrevtrt'
        tic
        [Mcmc.sampled_graphs, Mcmc.LL] =...
            learn_struct_mcmc_MH_SeqREVmove4('LS',LS, 'init_dag',init_dag,...
            'pa_limit',pa_limit,...
            'hprior',Hprior,...
            'rev',0.50,...
            'edirec',2,...
            'nsamples', nsamples, 'burnin', burnin,...
            'thinning',thinning,'runtime',runt);
        Mcmc.toc=toc;
end

if sum(isinf(Mcmc.LL))==0
    disp('job finished before time come')
end
Mcmc.init_dag=sparse(init_dag);

if savefile ==1
    save(Param.savepath.mcmc,'Mcmc')
end
end



